### ISSUE TITLE
How to stop the player without timer?

### ISSUE THREAD

**Issue by Salman-Official** [Yahhi/pomodoro_on_flutter#1]
I'm using AudioCache object to play the sound from assets folder, it's working perfectly fine but if I want to stop the sound without implementing the timer then how can it be possible?

**Comment by Salman-Official** [comment]
I'm using AudioPlayer object to play the sound from assets folder but it's not working. Following is the code to initialize the same and the error log - 

//code to initialize
audioPlayer.play(alarmAudioPath, isLocal: true);

//Error log

E/MethodChannel#xyz.luan/audioplayers(31837): Failed to handle method call
E/MethodChannel#xyz.luan/audioplayers(31837): java.lang.IllegalArgumentException: Unsupported value: java.lang.RuntimeException: Unable to access resource
E/MethodChannel#xyz.luan/audioplayers(31837): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:47)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#xyz.luan/audioplayers(31837): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AccessibilityBridge(31837): VirtualView node must not be the root node.

**Comment by Yahhi** [comment]
> I'm using AudioCache object to play the sound from assets folder, it's working perfectly fine but if I want to stop the sound without implementing the timer then how can it be possible?

Let's say you play it the same as in this project:
  static AudioCache player = new AudioCache();
then
    player.play(SettingsKeys.defaultAlarmAudioPath);

To pause it:
    player.fixedPlayer.pause();

**Comment by Salman-Official** [comment]
@Yahhi Thanks for the quick reply. I will check it and then respond.

**Comment by Salman-Official** [comment]
@Yahhi Thanks for your time, I got it.
